name: Hello World
on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: |
          echo "Hello, HI, ${{ vars.MY_NAME}}"
          echo "Hello, HI, ${{ secrets.DOCKER_PASSWORD}}"
  test:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Test Step
         run: echo "A Demo Test"
  deploy:
     runs-on: ubuntu-latest
     needs: test
     steps:
       - name: Deploy Step
         run: echo "A Demo Deploy"
     
        
