name: Terraform Dev Deploy
on: 
    pull_request:
        branches: 
            - develop
jobs:
    plan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.8.5

            - name: Aws Access using OIDC
              run: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::431655581666:role/github-oidc-udemy
                role-session-name: github-actions
                aws-region: eu-north-1

            - name: Terraform init
              run: terraform init
            - name: Terraform validate
              run: terraform validate
            - name: Terraform plan
              run: terraform plan 